wechat/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from .views import handleCheckSignature
from .debug import handleDebug
from .menu import handleMenuRequest


urlpatterns = [
    url(r'^checksignature$', handleCheckSignature),
    url(r'^menu', handleMenuRequest, name='handleMenuRequest'),
    url(r'^debug', handleDebug, name='handleDebug'),
]

newsletter/forms.py
from django import forms

from .models import SignUp

class ContactForm(forms.Form):
	full_name = forms.CharField(required=False)
	email = forms.EmailField()
	message = forms.CharField()

class SignUpForm(forms.ModelForm):
	class Meta:
		model = SignUp
		fields = ['full_name', 'email']
		### exclude = ['full_name']
	def clean_email(self):
		email = self.cleaned_data.get('email')
		email_base, provider = email.split("@")
		domain, extension = provider.split('.')
		# if not domain == 'USC':
		# 	raise forms.ValidationError("Please make sure you use your USC email.")
		if not extension == "edu":
			raise forms.ValidationError("Please use a valid .EDU email address")
		return email

	def clean_full_name(self):
		full_name = self.cleaned_data.get('full_name')
		#write validation code.
		return full_name

orders/forms.py
from django import forms
from django.contrib.auth import get_user_model

from .models import UserAddress
User = get_user_model()

class GuestCheckoutForm(forms.Form):
	email = forms.EmailField()
	email2 = forms.EmailField(label='Verify Email')

	def clean_email2(self):
		email = self.cleaned_data.get("email")
		email2 = self.cleaned_data.get("email2")

		if email == email2:
			user_exists = User.objects.filter(email=email).count()
			if user_exists != 0:
				raise forms.ValidationError("This User already exists. Please login instead.")			
			return email2
		else:
			raise forms.ValidationError("Please confirm emails are the same")

class AddressForm(forms.Form):
	billing_address = forms.ModelChoiceField(
			queryset=UserAddress.objects.filter(type="billing"),
			widget = forms.RadioSelect,
			empty_label = None #not show enmpty
			)
	shipping_address = forms.ModelChoiceField(
		queryset=UserAddress.objects.filter(type="shipping"),
		widget = forms.RadioSelect,
		empty_label = None,
		
		)

class UserAddressForm(forms.ModelForm):
	class Meta:
		model = UserAddress
		fields = [
			'street',
			'city',
			'state',
			'zipcode',
			'type'
		]

templates/about.html
{% extends "base.html" %}

{% block content %}
<div class='row'>
	<div class='col-sm-6 col-sm-offset-3'>
		<h1 class="text-center">About Us</h1>
		<div  style="text-align: left">
			<p>Hunan Cofoe Medical Technology Development Co.,Ltd is a professional medical devices high-tech technology type production enterprise which is specialized in household medical auxiliary rehabilitation appliance and household electronic surveillance products' R&D.</p>
			<p>
			We established a special R&D team in Germany, responsible for product development and design, the brand--"Cofoe" has been registered in the European Union. Currently, there are more than 60 categories products, the mainly R&D products are 6864 medical supplies and dressings and 6826 physical therapy and rehabilitation equipment, etc.</p>
			<p>
			15 types of wrist and arm electronic blood pressure monitor have got recognized at domestic and abroad market."Cofoe" products has been exported to more than 50 countries and regions in the world, well received by users.</p>
			<p>
			We will continue to create more technological, innovative and humanized rehabilitation auxiliary products to improve our own product system and the quality of life of the masses.</p>
			<p>
			"Be focus, Be professional." All of the Cofoe staffs will take the masses' health as own duty. Opening the market with quality,stabilizing the market with services,expanding the market with products, strive to become one of the home medical equipment manufacturers which possesses various products, best quality and best service,so that meet the market demand and the benefit of the general public.</p>
		</div>
		<hr>
		<p><b>Address:</b></p>
		<iframe src="sitemap" width="600" height="300" frameborder="0" scrolling="no"></iframe>
	</div>
</div>
{% endblock%}

templates/alert.html
<div class='container container-alert-flash'><div class='col-sm-3 col-sm-offset-8'><div class='alert alert-success alert-dismissible' role='alert'><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button>{{ message }}</div></div></div>

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    {% comment %}
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    {% endcomment %}
    <meta http-equiv="Content-Type" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no"/>
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>{% block head_title %}CodingSOHO{% endblock %}</title>

    {% block head_css_extend_before_main_css %}{% endblock %}

    {% include 'head_css.html' %}

    {% block head_css %}{% endblock %}

    <style>
    {% block style %}{% endblock %}
    </style>
      
  </head>

  <body>
    {% include 'navbar.html' %}

    {% block breadcrumb  %}
    <div class="container" style="padding: 10px 0 10px 0px; ">
        <ol class="breadcrumb" style="margin-bottom:0; background-color: white">
        {% for breadcrumb in request.breadcrumbs %}     
            {% if not forloop.last %}
            <li><a href="{{ breadcrumb.url }}">{{ breadcrumb.name }}</a></li>
            {% else %} 
            <li class="active">{{ breadcrumb.name }}</li>
            {% endif %}
        {% endfor %}        
        </ol>
    </div>  
    {% endblock %}

    {% block messages %}
      {% if messages %}
      <div class='container'>
        <div class='alert alert-success text-center alert-dismissible'>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            {% for message in messages %}
              <div class="{% if message.tags %} class='{{ message.tags }}'{% endif %}>">
                {% if 'capfirst' in message.tags %}
                {{ message|capfirst }}
                {% else %}
                {{ message }}
                {% endif %}
              </div>
            {% endfor %}
        </div>
      </div>
      {% endif %}
    {% endblock messages %}

    {% block jumbotron %}
    {% endblock %}

    {% block carousel %}  
    {% endblock %}
      
    <div class="container">
    <!-- <div class="container-fluid"> -->
      {% block content %}
      {% endblock %}
    </div>

{% comment %}
    <div class='container'>    
        <hr>
        <ul class="list-inline">
            友情链接：
            <li><a href="http://www.webdog.cn/" target="_blank">发现中国</a></li>   
            <li><a href="http://www.aboboo.com/" target="_blank">外语学习</a></li>   
            <li><a href="http://www.wuzheng.org/" target="_blank">无争围棋网</a></li>  
            <li><a href="http://www.guokr.com/" target="_blank">果壳网</a></li>  
            <li><a href="http://www.fuwo.com/" target="_blank">爱福窝</a></li>  
            <li><a href="http://www.guoku.com/" target="_blank">果库</a></li>  
            <li><a href="http://www.python88.com/" target="_blank">py社区</a></li> 
        </ul> 
    </div>
{% endcomment %}

    {% block footer %}
      {# include "footer.html" #}
    {% endblock %}

    {% include "javascript.html" %}   

    {% block javascript_extended %}
    {% endblock %}

    {% block head_js %}
    {% endblock %}

    <script>
    $(document).ready(function(){
        {% block jquery %}
 
        {% endblock %}
    });
    </script>

    <script type="text/javascript">
        {% block js %}

        {% endblock %}    
    </script>

    {% block jswotag %} <!-- if want to include a html file, double tag will break the structure-->
    {% endblock %}  


  </body>
</html>

templates/carousel.html
<style>
{% block style %}
.mycarousel {
    margin-bottom: 5px;
    padding-bottom: 1px;
}

.carousel-inner {
    /*height: 350px;*/
    background-repeat: no-repeat;
    background: no-repeat center center;    
}

.mycarousel img{
    /*display:block;*/
    width: 100%;
    height: auto;    
}

.item>img{
    text-align:center;
    vertical-align: middle;
    margin: auto;

	/*position: absolute;
	margin-left:5%;
	margin-right: 5%;
	margin-top: 5%;
	margin-bottom: 5%;	
	height:90%；
	width:90%；

	display: block;
	*/
}

{% endblock %}
</style>

<div class="mycarousel">
  <div class="container-fluid">
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner" role="listbox">
        {% for obj in objects %}
          {% if forloop.first %}<div class="item active">{% else %}<div class="item">{% endif %}
            <img src="{{obj.image.url}}" alt="{{obj.title}}">
            <div class="carousel-caption">
              {{obj.title}}
            </div>
          </div>
        {% endfor %}
      </div>

      <!-- Controls -->
      <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>
</div>

templates/footer.html
<style type="text/css">

	.foot-link{
		border: solid 1px #f2dede;
		border-left: none;
		border-right:none;
		background-color: #f8f8f8;
		padding: 10px 0 10px 0;
		text-align: left;
	}

	.foot-link ul{
		list-style:none; 
		margin:0;
		padding:0;
		padding-top: 1px;
		padding-bottom: 1px;
	}

	.footer-certifiate{
		padding: 30px 0px 30px 0px; 
		color:white; 
		background-color: #2d826f;
	}

	.footer hr {
    margin-top: 10px;
    margin-bottom: 10px;
    border: 0;
    border-top: 1px solid #eee;
    }

    .footer .form-group {
        margin-bottom: 5px;
    }

    .footer .form-control {
    height: 30px!important;
    padding: 6px 6px;
}
</style>


<div class="footer container-fluid" style="margin-top:30px">

	<div class="row foot-link"> 
	    <div class="col-sm-2 col-sm-offset-3">
	    	<br><b>FOLLOW US</b><hr>
	    	<img  class= 'img-responsive' style=" margin:0;" src='{{request.media}}footer/weixin.jpg'/>	
	    </div>
	    <div class="col-sm-2" >
	    	<br><b>ABOUT US</b><hr>
	    	<ul>		    	
		    	<li><a href="{% url 'ArticleListView' %}">News</a></li>
		    	<li><a href="{% url 'products' %}">Products</a></li>
		    	<li><a href="{% url 'about' %}">About us</a></li>
	    	</ul>
	    </div>
	    <div class="col-sm-2">
	    	<br><b>CONTACT US</b><hr>
	    	<ul>		    	
		    	<li>电话: 13888888888</li>
		    	<li>地址: 泰州</li>
		    	<li>联系人: 黄老板</li>
	    	</ul>	    
	    	
	    </div>

	    <div class="col-sm-3">
	    </div>

	    {% comment %}
	    <div class="col-sm-2">
	    	<br><b>FEEDBACK</b><hr>
	    	<form method='POST' action=''>{% csrf_token %}
				<div id="div_id_full_name" class="form-group"> 
					<label for="id_full_name" class="control-label ">Full name</label> 
					<div class="controls "> 
						<input class="textinput textInput form-control" id="id_full_name" name="full_name" type="text" /> 
					</div> 
				</div> 
				<div id="div_id_email" class="form-group"> 
					<label for="id_email" class="control-label  requiredField">Email<span class="asteriskField">*</span> </label> 
	                <div class="controls "> 
	                	<input class="emailinput form-control" id="id_email" name="email" type="email" /> 
	                </div> 
	            </div> 
	            <div id="div_id_message" class="form-group"> 
	            	<label for="id_message" class="control-label  requiredField">Message<span class="asteriskField">*</span> </label> 
	            	<div class="controls "> 
	            		<input class="textinput textInput form-control" id="id_message" name="message" type="text" /> 
	            	</div> 
	            </div>
				<input class = 'btn btn-primary' type='submit' value='Submit' />
			</form>
	    </div>
	    {% endcomment %}
	</div>
	<div class="row  text-center footer-certifiate">
		Copyright © 
	</div>
</div>

templates/form_fileupload.html
{% load crispy_forms_tags %}

<form id="form_upload"  enctype="multipart/form-data" action="/fileupload/uploadfile " method="POST"> {% csrf_token %}
    <img  id='img' class= 'img-responsive' src="{{object.get_image_url}}" />
    {{upload_form|crispy}}
    <div class="progress">
      <div class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%">
        0%
      </div>
    </div>        
    <div class="processing-file"></div>
    <br>
    <input id="buttonSubmit" class="btn btn-primary" type="submit" value="Upload" />        
</form>

templates/form_horizontal.html
<!--overwrite base.cc-->
<style>
input[type=submit]#create-sumit {
    color: #fff;
    background-color: #428bca ;
    background-image: none;
    border-color: #357ebd;
    height: 35px;
    width: 120px;
}
</style>

<form class="form-horizontal" {% if file %}enctype="multipart/form-data"{% endif %} method="POST" action={% if action %}{{action}}{% else %}''{% endif %} >{% csrf_token %}
    {% if form.errors %}
        <p style="color: #b75f33;">
            {{form.non_field_errors}}
        </p>
    {% endif %}

    {% for field in form %}
        {% if field.is_hidden %}
            <div>{{ field }}</div>
        {% else %}
            {% if field.errors %}<div class="error" style="color:#b75f33">{{ field.errors }}</div>{% endif %}
            <div class="field-area form-group list-unstyled list-inline  {% if field.errors %} error has-error{% endif %}">
                <div class="col-sm-2">
                    {{ field.label_tag }}
                </div>
                <div class="col-sm-10">
                    {{ field }} 
                </div>
            </div>
        {% endif %}            
    {% endfor %}
    <input id="create-sumit"  type="submit" name="submit" class="btn btn-primary pull-right" value={% if submitvalue %}{{submitvalue}}{% else %}"submit"{% endif %} />
</form>

templates/forms.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}


<div class='row'>
<div class ='col-sm-6 col-sm-offset-3'>
{% if title %}
<h1 class = '{% if title_align_center %}text-align-center{% endif %}'>{{title}}</h1>
{% endif %}
<form method='POST'  {% if file %}enctype="multipart/form-data"{% endif %} action=''>{% csrf_token %}
{{ form|crispy }}

<input class = 'btn btn-primary' type='submit' value='Submit' />
</form>
</div>
</div>
{% endblock %}

templates/head_css.html
{% load staticfiles %}

   <!-- Bootstrap core CSS -->
    <link href="http://lib.sinaapp.com/js/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet"> 
    <!-- <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"> -->

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/navbar-static-top.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>-->
    <link href="{% static 'js/ie-emulation-modes-warning.js' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <!-- <link rel="stylesheet" href="http://cdn.bootcss.com/font-awesome/4.2.0/css/font-awesome.min.css"> -->

    <link href="{% static 'css/custom.css' %}" rel="stylesheet">

    <link href="{% static 'css/jquery-ui.css' %}" rel="stylesheet">

templates/home.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% load i18n %}

{% block head_title %}Welcome | {{ block.super }} {% endblock %}

<style>
{% block style %}
.navbar-static-top {
  margin-bottom: 0px; 
}

.panel{
  border-left: none;
  border-right: none;
  border-bottom: none;
}

{% endblock %}
</style>

{% block breadcrumb  %}
{% endblock %}

{% block jumbotron %}    
  {% include "jumbotron.html" with featured_image=featured_image%}
{% endblock %}

<script type="text/javascript" charset="utf-8">
{% block jquery %}

{% endblock %}
</script>

{% block carousel %}  
  {% include "carousel.html" with objects=banners %}
{% endblock %}


{% block content %}
<br>

<div class= 'row'><div class="col-xs-12">
<div class="panel panel-info">
  <div class="panel-heading">
    <h3>Recommended Products</h3>
  </div>
  <div class="panel-body scale-product" >
    {% include "products/products.html" with object_list=products col_class_set="col-sm-2" %}
  </div>
  <div style="text-align: -webkit-center;">
    <p><a class="btn btn-default btn-lg" href="/products" role="button">More</a></p>
  </div>
</div>
</div></div>

<div class= 'row'><div class="col-xs-12">
<div class="panel panel-info">
  <div class="panel-heading">
    <h3>Featured Products</h3>
  </div>
  <div class="panel-body scale-product">
    {% include "products/products.html" with object_list=products2 %}
  </div>
</div>
</div></div>

{% endblock %}

<script>
    $(function(){
        $('.carousel').carousel();
    });
</script>

templates/jumbotron.html
<style>
{% block style %}

.jumbotron {
    margin-bottom: 5px;
    padding-top: 30px;
    padding-bottom: 10px;

    background-color: #5ACDFF !important;
    /*color : #F5F5F5;*/
    color : #000;
    {% if featured_image.make_image_background %} 
    background-image: url("{{ featured_image.image.url }}");
    background-repeat: no-repeat;
    background-color: #000;
    background-size: cover; /*stretch to adapt screen*/
    background-position-y: -272px;
    {% endif %}    
}

.jumbotron .img-responsive {
    max-height: 200px;
    text-align: center;  
    vertical-align: middle;
    margin: auto;   
}
{% endblock %}
</style>

    {% if featured_image %} 
    <div class="jumbotron">
        <div class="container">
            <div class="row">
                <div class='{% if featured_image.make_image_background %} col-sm-12 {% else %} col-sm-6 {% endif %} text-center {% if featured_image.text_right %} pull-right {% endif %}'>
                    <h1>{{ featured_image.product.title }}</h1>
                    <p>{{ featured_image.product.description }}</p>
                    <p>
                        <a class="btn btn-lg btn-primary" href="{{ featured_image.product.get_absolute_url }}" role="button">More Details &raquo;</a>
                    </p>
                </div>
                {% if not featured_image.make_image_background %} 
                <div class='col-sm-6'>
                    <img src="{{ featured_image.image.url }}" class='img-responsive'  />
                </div>
                {% endif %}
            </div>
        </div>
    </div>    
    {% else %}
    <div class="jumbotron">
        <div class="container">
            <div class="row">
                <div class='col-sm-6'>
                    <h1>crowd founding</h1>
                    <p>Welcome to Crowd Founding. Join Us today.</p>
                    <p>
                        <a class="btn btn-lg btn-primary" href="" role="button">Join us &raquo;</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
    {% endif %}    

templates/languages_select_part.html
{% load staticfiles %}
{% load langs %}

{% if languages %}
<form class="navbar-form navbar-left" id="language-select-form" method="post" action="{% url 'setlang' %}">{% csrf_token %}
	<select class="dropdown form-control" onchange="this.form.submit();" name="language">
		{% for lang in languages %}
		<option value="{{ lang.code }}" {% if lang.code == default %}selected="selected"{% endif %}>{{ lang.name_local }}</option>
		{% endfor %}
	</select>
	<input name="next" type="hidden" value="{{ request.get_full_path|strip_lang }}" />
</form>
{% endif %}

templates/map.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312" />
<meta name="keywords" content="百度地图,百度地图API，百度地图自定义工具，百度地图所见即所得工具" />
<meta name="description" content="百度地图API自定义地图，帮助用户在可视化操作下生成百度地图" />
<title>百度地图API自定义地图</title>
<!--引用百度地图API-->
<style type="text/css">
    html,body{margin:0;padding:0;}
    .iw_poi_title {color:#CC5522;font-size:14px;font-weight:bold;overflow:hidden;padding-right:13px;white-space:nowrap}
    .iw_poi_content {font:12px arial,sans-serif;overflow:visible;padding-top:4px;white-space:-moz-pre-wrap;word-wrap:break-word}
</style>
<script type="text/javascript" src="http://api.map.baidu.com/api?key=&v=1.1&services=true"></script>
</head>

<body>
  <!--百度地图容器-->
  {% comment %}
  <div style="width:697px;height:550px;border:#ccc solid 1px;" id="dituContent"></div>
  {% endcomment %}
  <div style="width:280px;height:200px;border:#ccc solid 1px;" id="dituContent"></div>
  
</body>
<script type="text/javascript">
    //创建和初始化地图函数：
    function initMap(){
        createMap();//创建地图
        setMapEvent();//设置地图事件
        addMapControl();//向地图添加控件
    }
    
    //创建地图函数：
    function createMap(){
        var map = new BMap.Map("dituContent");//在百度地图容器中创建一个地图
        var point = new BMap.Point(119.929651,32.462147);//定义一个中心点坐标
        map.centerAndZoom(point,17);//设定地图的中心点和坐标并将地图显示在地图容器中
        window.map = map;//将map变量存储在全局
    }
    
    //地图事件设置函数：
    function setMapEvent(){
        map.enableDragging();//启用地图拖拽事件，默认启用(可不写)
        map.enableScrollWheelZoom();//启用地图滚轮放大缩小
        map.enableDoubleClickZoom();//启用鼠标双击放大，默认启用(可不写)
        map.enableKeyboard();//启用键盘上下左右键移动地图
    }
    
    //地图控件添加函数：
    function addMapControl(){
        //向地图中添加缩放控件
	var ctrl_nav = new BMap.NavigationControl({anchor:BMAP_ANCHOR_TOP_LEFT,type:BMAP_NAVIGATION_CONTROL_LARGE});
	map.addControl(ctrl_nav);
        //向地图中添加缩略图控件
	var ctrl_ove = new BMap.OverviewMapControl({anchor:BMAP_ANCHOR_BOTTOM_RIGHT,isOpen:1});
	map.addControl(ctrl_ove);
        //向地图中添加比例尺控件
	var ctrl_sca = new BMap.ScaleControl({anchor:BMAP_ANCHOR_BOTTOM_LEFT});
	map.addControl(ctrl_sca);
    }
    
    
    initMap();//创建和初始化地图
</script>
</html>