products/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import TemplateView

from .views import ProductDetailView, ProductListView, ProductCreateView, VariationListView

urlpatterns = [
    # Examples:

    url(r'^$', ProductListView.as_view(), name='products'),
    url(r'^create$', ProductCreateView.as_view(), name='products_create'),
    url(r'^(?P<pk>\d+)/$', ProductDetailView.as_view(), name='product_detail'),
    #url(r'^(?P<id>\d+)', 'products.views.product_detail_view_func', name='product_detail_function'),
    url(r'^(?P<pk>\d+)/inventory/$', VariationListView.as_view(), name='product_inventory'),   
    url(r'^exchangerule$',
        TemplateView.as_view(template_name='products/exchange_rule.html'),
        name='exchange_rule'),     
]

wechat/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from .views import handleCheckSignature
from .debug import handleDebug
from .menu import handleMenuRequest


urlpatterns = [
    url(r'^checksignature$', handleCheckSignature),
    url(r'^menu', handleMenuRequest, name='handleMenuRequest'),
    url(r'^debug', handleDebug, name='handleDebug'),
]

products/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import post_save
from django.utils.safestring import mark_safe
from django.utils.text import slugify

class ProductQuerySet(models.query.QuerySet):
	def active(self):
		return self.filter(active=True)


class ProductManager(models.Manager):
	def get_queryset(self):
		return ProductQuerySet(self.model, using=self._db)

	def all(self, *args, **kwargs):
		return self.get_queryset().active()

	def get_related(self, instance):
		products_one = self.get_queryset().filter(categories__in=instance.categories.all())
		products_two = self.get_queryset().filter(default=instance.default)
		qs = (products_one | products_two).exclude(id=instance.id).distinct()
		return qs

# Create your models here.
class Product(models.Model):
	title = models.CharField(max_length=120)
	description = models.TextField(blank=True, null=True)
	price = models.DecimalField(decimal_places=2, max_digits=20)
	active = models.BooleanField(default=True)
	categories = models.ManyToManyField('Category', blank=True)
	default = models.ForeignKey('Category', related_name='default_category', null=True, blank=True)
	
	objects = ProductManager()

	class Meta:
		ordering = ["-title"]

	def __unicode__(self): #def __str__(self):
		return self.title 

	def get_absolute_url(self):
		return reverse("product_detail", kwargs={"pk": self.pk})

	def get_image_url(self):
		img = self.productimage_set.first()
		if img:
			return img.image.url
		return img #None

	def get_inventory_url(self):
		return reverse("product_detail", kwargs={"pk": self.pk})

class Variation(models.Model):
	product = models.ForeignKey(Product)
	title = models.CharField(max_length=120)
	price = models.DecimalField(decimal_places=2, max_digits=20)
	sale_price = models.DecimalField(decimal_places=2, max_digits=20, null=True, blank=True)
	active = models.BooleanField(default=True)
	inventory = models.IntegerField(null=True, blank=True) #refer none == unlimited amount

	def __unicode__(self):
		return self.title

	def get_price(self):
		if self.sale_price is not None:
			return self.sale_price
		else:
			return self.price

	def get_html_price(self):
		if self.sale_price is not None:
			html_text = "<span class='sale-price'>%s</span> <span class='og-price'>%s</span>" %(self.sale_price, self.price)
		else:
			html_text = "<span class='price'>%s</span>" %(self.price)
		return mark_safe(html_text)

	def get_absolute_url(self):
		return self.product.get_absolute_url()

	def add_to_cart(self):
		return "%s?item=%s&qty=1" %(reverse("cart"), self.id) #here cart is url name

	def remove_from_cart(self):
		return "%s?item=%s&qty=1&delete=True" %(reverse("cart"), self.id)

	def get_title(self):
		return "%s - %s" %(self.product.title, self.title)



def product_post_saved_receiver(sender, instance, created, *args, **kwargs):
	product = instance
	variations = product.variation_set.all()
	if variations.count() == 0:
		new_var = Variation()
		new_var.product = product
		new_var.title = "Default"
		new_var.price = product.price
		new_var.save()


post_save.connect(product_post_saved_receiver, sender=Product)

def image_upload_to(instance, filename):
	title = instance.product.title
	slug = slugify(title)
	basename, file_extension = filename.split(".")
	new_filename = "%s-%s.%s" %(basename[:60], instance.id, file_extension)
	#print title, slug, basename, file_extension, new_filename
	#print instance,filename
	return "products/%s/%s/%s" %(instance.product.default.title.lower(), slug[:40], new_filename)


class ProductImage(models.Model):
	product = models.ForeignKey(Product)
	image = models.ImageField(upload_to=image_upload_to)

	def __unicode__(self):
		return self.product.title
		
class Category(models.Model):
	title = models.CharField(max_length=120, unique=True)
	slug = models.SlugField(unique=True)
	description = models.TextField(null=True, blank=True)
	active = models.BooleanField(default=True)
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)

	def __unicode__(self):
		return self.title
		
	def get_absolute_url(self):
		return reverse("category_detail", kwargs={"slug": self.slug })


def image_upload_to_featured(instance, filename):
	title = instance.product.title
	slug = slugify(title)
	basename, file_extension = filename.split(".")
	new_filename = "%s-%s.%s" %(basename[:60], instance.id, file_extension)
	return "products/featured/%s/%s" %(slug[:40], new_filename)

class ProductFeatured(models.Model):
	product = models.ForeignKey(Product)
	image = models.ImageField(upload_to=image_upload_to_featured)
	title = models.CharField(max_length=120, null=True, blank=True)
	text = models.CharField(max_length=220, null=True, blank=True)
	text_right = models.BooleanField(default=False)
	text_css_color = models.CharField(max_length=6, null=True, blank=True)
	show_price = models.BooleanField(default=False)
	make_image_background = models.BooleanField(default=False)
	active = models.BooleanField(default=True)

	def __unicode__(self):
		return self.product.title

products/views.py
#encoding=utf-8
from django.contrib import messages
from django.db.models import Q
from django.http import Http404
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import FormView, CreateView
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .forms import ProductCreateForm, ProductImageForm
from .models import Category, ProductImage
from django.utils.text import slugify
from django.core.urlresolvers import reverse

from django_filters import FilterSet, CharFilter, NumberFilter
# Create your views here.
from .forms import VariationInventoryFormSet, ProductFilterForm
from .mixins import StaffRequiredMixin, PermissionRequiredMixin

from .models import Product, Variation, Category
from django.utils.translation import gettext_lazy as _


class CategoryListView(ListView):
    model = Category
    queryset = Category.objects.all()
    template_name = "products/product_list.html"


class CategoryDetailView(DetailView):
    model = Category

    def get_context_data(self, *args, **kwargs):
        context = super(CategoryDetailView, self).get_context_data(*args, **kwargs)
        obj = self.get_object()
        product_set = obj.product_set.all()
        default_products = obj.default_category.all()
        products = ( product_set | default_products ).distinct()
        context["products"] = products
        context["categories"] = Category.objects.all()
        return context



class VariationListView(StaffRequiredMixin, ListView):
    model = Variation
    queryset = Variation.objects.all()

    def get_context_data(self, *args, **kwargs):
        context = super(VariationListView, self).get_context_data(*args, **kwargs)
        context["formset"] = VariationInventoryFormSet(queryset=self.get_queryset()) 
        return context

    def get_queryset(self, *args, **kwargs):
        product_pk = self.kwargs.get("pk")
        if product_pk:
            product = get_object_or_404(Product, pk=product_pk)
            queryset = Variation.objects.filter(product=product) 
        return queryset

    def post(self, request, *args, **kwargs):
        formset = VariationInventoryFormSet(request.POST, request.FILES)
        if formset.is_valid():
            formset.save(commit=False)
            for form in formset:
                new_item = form.save(commit=False)
                #if new_item.title:
                product_pk = self.kwargs.get("pk")
                product = get_object_or_404(Product, pk=product_pk)
                new_item.product = product
                new_item.save()
                
            messages.success(request, "Your inventory and pricing has been updated.") 
            return redirect("products")
        raise Http404

class ProductFilter(FilterSet):
    title = CharFilter(name='title', lookup_type='icontains', distinct=True)
    category = CharFilter(name='categories__title', lookup_type='icontains', distinct=True)
    category_id = CharFilter(name='categories__id', lookup_type='icontains', distinct=True)
    min_price = NumberFilter(name='variation__price', lookup_type='gte', distinct=True) # (some_price__gte=somequery)
    max_price = NumberFilter(name='variation__price', lookup_type='lte', distinct=True)
    class Meta:
        model = Product
        fields = [
            'min_price',
            'max_price',
            'category',
            'title',
            'description',
        ]


def product_list(request):
    qs = Product.objects.all()
    ordering = request.GET.get("ordering")
    if ordering:
        qs = Product.objects.all().order_by(ordering)
    f = ProductFilter(request.GET, queryset=qs)
    return render(request, "products/product_list.html", {"object_list": f })


class FilterMixin(object):
    filter_class = None
    search_ordering_param = "ordering"

    def get_queryset(self, *args, **kwargs):
        try:
            qs = super(FilterMixin, self).get_queryset(*args, **kwargs)
            return qs
        except:
            raise ImproperlyConfigured("You must have a queryset in order to use the FilterMixin")

    def get_context_data(self, *args, **kwargs):
        context = super(FilterMixin, self).get_context_data(*args, **kwargs)
        qs = self.get_queryset()
        ordering = self.request.GET.get(self.search_ordering_param)
        if ordering:
            qs = qs.order_by(ordering)
        filter_class = self.filter_class
        if filter_class:
            f = filter_class(self.request.GET, queryset=qs)
            context["object_list"] = f
        return context

class ProductListView(FilterMixin, ListView):
    model = Product
    queryset = Product.objects.all()
    filter_class = ProductFilter

    def get_context_data(self, *args, **kwargs):
        context = super(ProductListView, self).get_context_data(*args, **kwargs)
        context["now"] = timezone.now()
        context["query"] = self.request.GET.get("q") #None
        context["filter_form"] = ProductFilterForm(data=self.request.GET or None)        
        context["categories"] = Category.objects.all()        
        return context

    def get_queryset(self, *args, **kwargs):
        qs = super(ProductListView, self).get_queryset(*args, **kwargs)
        query = self.request.GET.get("q")
        if query:
            qs = self.model.objects.filter(
                Q(title__icontains=query) |
                Q(description__icontains=query)
                )
            try:
                qs2 = self.model.objects.filter(
                    Q(price=query)
                )
                qs = (qs | qs2).distinct()
            except:
                pass
        return qs

    def dispatch(self, request, *args, **kwargs):
        ''' need config i18n before use this
        request.breadcrumbs([
            (_("Home"),reverse("home", kwargs={})),
            (_("product"),request.path_info),
        ])
        '''

        request.breadcrumbs([
            ("Home",reverse("home", kwargs={})),
            ("product",request.path_info),
        ])
        return super(ProductListView, self).dispatch(request,args,kwargs)

import random
class ProductDetailView(DetailView):
    model = Product
    #template_name = "product.html"
    #template_name = "<appname>/<modelname>_detail.html"
    def get_context_data(self, *args, **kwargs):
        context = super(ProductDetailView, self).get_context_data(*args, **kwargs)
        instance = self.get_object()
        #context["related"] = Product.objects.get_related(instance).order_by("?")[:6]
        context["related"] = sorted(Product.objects.get_related(instance)[:6], key= lambda x: random.random())
        context["images"] = ProductImage.objects.filter(product=instance)[1:]
        return context

    def dispatch(self, request, *args, **kwargs):
        ''' need config i18n before use this
        request.breadcrumbs([
            (_("Home"),reverse("home", kwargs={})),
            (_("product"),request.path_info),
        ])
        '''

        instance = self.get_object()
        request.breadcrumbs([
            ("Home",reverse("home", kwargs={})),
            ("product",reverse("products", kwargs={})),
            (instance.title,request.path_info),
        ])
        return super(ProductDetailView, self).dispatch(request,args,kwargs)


def product_detail_view_func(request, id):
    #print "coming"
    #product_instance = Product.objects.get(id=id)
    product_instance = get_object_or_404(Product, id=id)
    try:
        product_instance = Product.objects.get(id=id)
    except Product.DoesNotExist:
        raise Http404
    except:
        raise Http404

    template = "products/product_detail.html"
    context = {    
        "object": product_instance
    }

    return render(request, template, context)


from PIL import Image 
from django.conf import settings
import os
def upload_to(filename, title, id):
    if filename:
        img=Image.open(filename)
        slug = slugify(title)
        basename, file_extension = filename.name.split(".")
        new_filename = "%s-%s.%s" %(slug, id, file_extension)        
        photoname = os.path.join("products", slug, new_filename)
        if settings.USE_SAE_BUCKET: #'SERVER_SOFTWARE' in os.environ: 
            pass
        else:
            photopath = os.path.join(settings.MEDIA_ROOT, "products", slug)
            if not os.path.exists(photopath):
                os.makedirs(photopath)
        return photoname

class ProductCreateView(PermissionRequiredMixin, CreateView):
    template_name = 'products/product_create.html'
    form_class = ProductCreateForm
    success_url = "/products"


    def get_context_data(self, *args, **kwargs):
        context = super(ProductCreateView, self).get_context_data(*args, **kwargs)
        context["image_form"] = ProductImageForm()
        return context

    def get_form(self, *args, **kwargs):
        form = super(ProductCreateView, self).get_form(*args, **kwargs)

        form.fields['categories'].queryset  = Category.objects.all()
        form.fields['default'].queryset  = Category.objects.all()

        return form

    def post(self, request, *args, **kwargs):
        postresult = super(ProductCreateView, self).post(request, *args, **kwargs)

        if 1:
            in_mem_image_file=request.FILES['image']     
            if in_mem_image_file:
                photoname = upload_to(in_mem_image_file, self.object.title, self.object.id)

                if settings.USE_SAE_BUCKET: #'SERVER_SOFTWARE' in os.environ: 
                    from sae import storage
                    #from sae.storage import Bucket
                    #bucket = Bucket('media')
                    from saewrapper.storage.bucket import SAEBucket
                    SAEBucket().put_object(photoname,in_mem_image_file.file.getvalue())
                    #object_content = bucket.get_object_contents(photoname) 
                else:

products/templates/products/category_detail.html
{% extends "base.html" %}

{% block content %}

<h3>{{ object }}</h3>


<div class = 'row'>
    {% for categoy in categories %}
		<div class='col-xs-2'>
			{% include "products/product_thumbnail.html" with product=categoy %}
		</div>
	{% cycle '' '' '</div><div class="row">'%} 
    {% endfor %}

</div>

<div class = 'row'>
    {% for product in products %}
		<div class='col-xs-4'>
			{% include "products/product_thumbnail.html" with product=product price=True %}
		</div>
	{% cycle '' '' '</div><div class="row">'%} 
    {% endfor %}

</div>
{% endblock %}

products/templates/products/exchange_rule.html
{% extends "products/product_list.html" %}

{% block content-center %}
	This is exhange rule
{% endblock %}

products/templates/products/product_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}


<div class='row'>
<div class ='col-sm-6 col-sm-offset-3'>
{% if title %}
<h1 class = '{% if title_align_center %}text-align-center{% endif %}'>{{title}}</h1>
{% endif %}
<form method='POST' enctype="multipart/form-data" action=''>{% csrf_token %}
{{ form|crispy }}
{{image_form.as_p}}
<input class = 'btn btn-primary' type='submit' value='Submit' />
</form>
</div>
</div>
{% endblock %}

products/templates/products/product_detail.html
{% extends "base.html" %}

<style type="text/css">
{% block style %}
	div.text-detail{
		color: #2d826f;
	}
{% endblock %}	
</style>

<script>
{% block jquery %}


function setPrice(){
	var price = $(".variation_select option:selected").attr("data-price")

	var sale_price = $(".variation_select option:selected").attr("data-sale-price")
	if (sale_price != "" && sale_price != "None" && sale_price != null ) {
	//$("#price").html("<h3>" + sale_price + " <small style='color:red;text-decoration:line-through;'>Original Price:" + price  + "</small></h3>");
	$("#price").html("<h3>" + sale_price + " <small class='og-price'>" + price  + "</small></h3>");
	} else {
	$("#price").html(price);
	}
}
setPrice()

$(".variation_select").change(function(){
	setPrice();
	// var img = $(".variation_select option:selected").attr("data-img")
	// $("img").attr("src", img);
})

// ajax add to cart

$("#submit-btn").click(function(event){
	event.preventDefault();
	var formData = $("#add-form").serialize();
	console.log(formData);
	$.ajax({
		type: "GET", // "POST"
		url: "{% url 'cart' %}",
		data: formData,
		success: function(data) {
			//console.log(data)
			//$("#jquery-message").text("Added " + data.item_added + " Deleted " + data.deleted)
			showFlashMessage(data.flash_message);
			updateCartItemCount();
		}, 
		error: function(response, error) {
			// console.log(response)
			// console.log(error)
			$("#add-form").submit()
		}
	})

	// $("#add-form").submit() # it will go to the next page
})

{% endblock %}
</script>

{% block content %}

<div class='row'>
	<div class='col-sm-8'> 
		<h2><small>{{object.title}}</small></h2>
		<!-- {% if object.productimage_set.count > 0 %}
		<div>
			{% for img in object.productimage_set.all %}
			<img  id='img' class= 'img-responsive' src="{{img.image.url}}"/>
			{% endfor %}
		</div>
		{% endif %} --> 
		{% if object.get_image_url %}
		<div>
			<img  id='img' class= 'img-responsive' src='{{ object.get_image_url }}'/>
		</div>
		{% endif %}		
		<p class='lead'>
			{{object.description|linebreaks}}
		</p>

		<div>
			{% if images.count > 0 %}
			<div class="text-center text-detail"><h2>Product Details</h2></div>
			{% endif %}
			{% for img in images %}
			<div>
				<img  class= 'img-responsive' style=" margin:auto;" src='{{img.image.url}}'/>				
			</div>
			{% endfor %}
		</div>
	</div>
	<div class='col-sm-4'>	
		<form id='add-form' method='GET' action="{% url 'cart' %}"> <!-- add form for AJAX -->
			<p id='jquery-message' class='lead'></p>
			{% if object.variation_set.count > 1 %}
				<h3 id='price'>{{ object.variation_set.first.price }}</h3>		
				<select  name='item' class='form-control variation_select'>    
					{% for vari_obj in object.variation_set.all %}
				    <!-- <option data-img="http://www.spirit1059.com/pics/Feeds/Articles/2015611/118317/Beach.jpg" data-price="{{ vari_obj.price }}" value="{{ vari_obj.id }}">{{ vari_obj }}</option> -->
					<option  data-sale-price="{{ vari_obj.sale_price }}" data-price="{{ vari_obj.price }}" value="{{ vari_obj.id }}">{{ vari_obj }}</option>
					{% endfor %}
				</select>
			{% else %}
				<input type="hidden" name='item' value='{{ object.variation_set.first.id }}' /> <!-- need to be added in this section -->
				<h3 id='price'>{% if object.variation_set.first.sale_price %}
					{{ object.variation_set.first.sale_price  }}
					<small class='og-price'>{{ object.variation_set.first.price }}</small>
					{% else %}			
					{{ object.variation_set.first.price }}
					{% endif %}
				</h3>
			{% endif %}
			<br/>
			<input class='form-control' type='number' name='qty' value='1' />
			<br/>	
			<input id='submit-btn' type='submit' value='Add to Cart' class='btn btn-default' />  <!-- submit-btn for AJAX -->
		</form>

		<br/>
		<hr/>
		<p>
			Share<br/>
			<a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}">
			<i class="fa fa-facebook-square fa-3x"></i></a>

			<i class="fa fa-twitter-square fa-3x"></i>

			<a href="">
			<i class="fa fa-weixin fa-3x"></i></a>
		</p>

		<hr/>
		<h4>Related Products</h4>
		<div class='row'>
		{% for product in related %} 
			<div class='col-xs-6'>
				{% include "products/product_thumbnail.html" with product=product price="True" %}
			</div>
		{% cycle '' '</div><div class="row">'%}
		{% endfor %}
		</div>
	</div>

	<hr/>
	<h4><a href="{{object.get_inventory_url}}">Inventory</a></h4>

</div>
{% endblock %}

products/templates/products/product_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load pagination_tags %}

{% block content %}

<style type="text/css">

a:link {text-decoration: none;}
a:visited {text-decoration: none;}
a:active {text-decoration: none;}
a:hover {text-decoration: none;}

div.categorylist{
	margin-right: 0px; /* if the value > 0, then next div will move to next line*/
	padding: 5px 8px; 
	
	/*
	min-width : 30px; 
	display: inline-block;

	background-color: #dff0d8; 
	border:solid;
	border-width : 1px;
	border-color : #D6CCCC;	
	*/
}

.category-content .category-body .categorylist:hover{
	background-color: #d9edf7;
}

.category-content{
	
	/*border-bottom: solid 1px #c3e695;
	margin-bottom: 5px; */
	text-decoration: none; 
	outline: none;
	border-radius: 2px;
	border: solid 1px #d9edf7;
	overflow:hidden;
}

.category-content .category-suffix{
	border-right: solid 1px #d9edf7;
	margin-bottom:-10000px; 
	padding-bottom:10000px;
	line-height: 100%;
	background-color: #d9edf7;
	/*
	
	float:left; 
	width: 150px; 
	position:absolute; */
}

.category-content .category-body{	
	margin-bottom:-10000px; 
	padding-bottom:10000px;
	/*	
	border-bottom: solid 1px #c3e695;
	float:left; margin-left:150px; width: 100%*/
}

.category-content .category-body .active{	
	/*
	background-color: #d9edf7;
	font: bold;
	*/
}

.products-thumbnail{
	/*clear:both*/
}
</style>

<div class='col-sm-3 col-md-2'>
	<nav class="navbar navbar-default">
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="#">Search</a>
	    </div>

	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<form method="GET" action="{% url 'products' %}">
				{{ filter_form|crispy }}
				<input type='hidden' name='q' value='{{ request.GET.q }}' />
				<input type='submit' value='Apply Filter' class='btn btn-default'>
			</form>
			<a href="{% url 'products' %}">Clear Filters</a>    
	    </div>
	</nav>
</div>

<div class='col-sm-9 col-md-10 container'>

	{% block content-center %}
	<div class='row category-content text-center'>
		<div class='category-suffix categorylist col-xs-3 col-sm-3 col-md-2'>
			<a href='{% url "categories" %}'>Categories</a>
		</div>
		<div class='category-body  col-xs-9 col-sm-9 col-md-10'>
			<div class="row">
				<div class='col-xs-4 col-md-2 categorylist active'>
					<a href="{% url 'products' %}">All Products</a>
				</div>				

				{% for category in categories%}
				<div class='col-xs-4 col-md-2 categorylist'>
					<a href="{% url 'products' %}?category_id={{category.id}}" style="display: block; " >{{category}}</a>
				</div>
				{% cycle '' '' '' '' '' '</div><div class="row">'%} 
				{% endfor %}
			</div>
			
		</div>
	</div>

	<div class="row products-thumbnail">
		{% autopaginate object_list 6 %}
		{% if object_list.count == 0 %}
			Nothing found
		{% else %}
			{% include "products/products.html" with object_list=object_list %}
		{% endif %}
		<div class="text-center">
		{% paginate %}
		</div>
	</div>

	<small><a href='{% url "exchange_rule" %}'>Exchange Rule</a></small> 

	{% if perms.products.add_product %}
	<div class="row">
		<h1 >
		<small><a href='{% url "products_create" %}'>New Product</a></small> 
		</h1>	
	</div>
	{% endif %}
	
	{% endblock %}
</div>

{% endblock %}

products/templates/products/product_thumbnail.html
<style type="text/css">

 .thumbnail :hover img{

    opacity: 0.4;
    filter: alpha(opacity=40);
 	margin: 0px 0px 0px -10px;
 	transition-property: margin,opacity; 
 	transition-duration: 0.5s; 
 	transition-timing-function: ease;

/*    
    margin: 0px 2px 0px 0px; 
    -moz-transition-duration: 5s; 
    -webkit-transition-duration: 5s; 
    -o-transition-duration: 5s;  
    -moz-transition-timing-function: ease; 
    -webkit-transition-timing-function: ease; 
    -o-transition-timing-function: ease;  
*/   	
}

 .thumbnail:hover  img {

 }


div.scale-product .thumbnail :hover img{
    -webkit-transform:scale(1.1) rotate(0deg); 
    -moz-transform:scale(1.1) rotate(0deg); 
    -o-transform:scale(1.1) rotate(0deg); 
    -webkit-transition:all 2s; 
    -moz-transition:all 2s; 
    -o-transition:all 2s;   
    margin: 0px; 
    opacity: 1;
}

.thumbnail img{
	border-radius: 3px;
}

.thumbnail{
	border: none;
}

</style>

<div class="thumbnail text-center">
	{% if product.get_image_url %} 
		<a href='{{ product.get_absolute_url }}'><div class="pdb img-center"><img  id='img' class= 'img-responsive' src='{{product.get_image_url}}'/></div></a><br/>
	{% endif %}	

	{% if price == "True" %}
		{{ product.variation_set.first.get_html_price }}
	{% endif %}	

	<h5><a href='{{ product.get_absolute_url }}'>{{product.title}}</a></h5>	
</div>

products/templates/products/products.html
<div class='row'>
	{% for product in object_list %}
		<div class='col-xs-12 {% if col_class_set%}{{col_class_set}}{% else %}col-sm-3{% endif %}'>
			{% include "products/product_thumbnail.html" with product=product price="True" %}
		</div>
		{% if not col_class_set %}
		{% cycle '' '' '' '</div><div class="row">'%} 
		{% endif %}	
	{% endfor %}
</div>

products/templates/products/variation_list.html
{% extends "base.html" %}

{% block content %}

<table class='table'>
	{% for object in object_list %}
	<tr>
		<td><a href='{{ object.get_absolute_url }}'>{{ object.title }}</a></td>
		<td>{{ object.inventory }}</td>
	</tr>
	{% endfor %}
</table>

<form method="POST" action=""> {% csrf_token %}
	{{ formset.management_form }}
	{% for form in formset %}
	{{ form.instance.product.title }}
	{{ form.instance.title }}
	{{ form.as_p }}
	{% endfor %}
	<input type="submit" value='Update' class='btn' />
</form>

{% endblock %}